[book]
src = "src"
title = "Reserve Developer Documentation"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = [
    "book.css",
    "custom.css",
]
git-repository-url = "https://github.com/reserve-protocol/protocol"

[output.html.fold]
enable = true