#!/bin/bash -eu

# cd to project root
while [ ! -d .git -a `pwd` != "/" ]; do cd ..; done

# strictly solhint system code
git ls-files | egrep 'contracts/.*\.sol' | \
  xargs yarn exec solhint

# more-gently solhint test code
git ls-files | egrep 'contracts/fuzz.*\.sol' | \
    xargs yarn exec solhint \
          --config contracts/fuzz/.solhint.json \
          --ignore-path contracts/fuzz/.solhintignore
