#!/usr/bin/env python3
# Converts solidity dynamic libraries into static libraries for use with echidna
# (While making lots of assumptions about how that's to be done!)
from sys import stdin, argv
import re

# states
READING_HEADER = "READING_HEADER"
READING_CODE = "READING_CODE"

NO_COMMIT = f"""
/* DO_NOT_COMMIT. DO NOT EDIT THIS FILE.
 *
 * This file has been generated by {argv[0]} for use with echidna-test. Any
 * changes to this file will be discarded. Make changes to the original file
 * instead; it can be found in the same directory. */"""

state = READING_HEADER

for line in stdin:
    if state == READING_HEADER:
        if re.match(r"///* +SPDX-License-Identifier", line) or re.match("pragma", line):
            print(line, end="")
            continue
        else:
            print(NO_COMMIT)
            state = READING_CODE
    if state == READING_CODE:
        line = re.sub(r"\b(public|external)\b", "internal", line)
        print(line, end="")
