#!/usr/bin/env bash -euo pipefail

# Note: This script requires slither installed using solc 0.8.9
function require() {
    hash $1 2> /dev/null || ( echo >&2 "I require $1 but I cannot find it."; exit 1 )
}

require slither

# cd to project root
while [ ! -d .git -a `pwd` != "/" ]; do cd ..; done



# Run from inside `tools` so that the slither config files can live there
cd tools && slither ../
