name: Generate and Deploy Reserve Docs to Vercel

on:
  push:
    branches:
      - master

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install node dependencies
        run: yarn install
        shell: bash

      - name: Setup Forge config
        run: forge config --config-path tools/docgen/foundry.toml
        shell: bash

      - name: Generate docs
        run: forge doc --build --out tools/docgen
        shell: bash

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Change working directory & deploy
        run: vercel --cwd tools/docgen/book --yes --prod --token=${{ env.VERCEL_TOKEN }}